# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# The public documentation URL, used for sitemap.xml
headerbaseurl: //www.nativescript.org

navigation:
## List your directory names and order here, like this:
    intro:
        position: 1
        title: Introduction
    getting-started:
        position: 2
        title: Get Started
    user-guide:
        position: 3
        title: User Guide
    user-guide/code-signing:
        position: 3.5
        title: Code Signing
    user-guide/code-signing/code-signing-for-ios:
        position: 3.6
        title: Code Signing for iOS Apps
    techniques:
        position: 4
        title: Techniques
    
## The application virtual path
baseurl: /sidekick
   
## The highlighting in the header   
skselected: "selected"

## The product name
productName: "NativeScript Sidekick"
    
## Assign layout and category per different paths
defaults:
-
    scope:
        path: ""
    values:
        layout: "page"
        category: "default"

# Aliases available in the markdown template. The below will expand {{site.foo}} to Bar in the output
"ns": "NativeScript"
"sk": "Sidekick"
"ns-sk": "NativeScipt Sidekick"
"ns-cli": "NativeScript CLI"
        
# Assets pipeline configuration
assets:
    cachebust: soft
    js_compressor: uglifier

## Do not edit below this line
safe: false
markdown: MarkdownProcessor
kramdown:
    toc_levels: 2..3
    smart_quotes: ["quot", "quot", "quot", "quot"]
    input: GFM

